### PR TITLE
Optimize message printing and memory usage

### PR DESCRIPTION
**Pull request by jimbozhang**
- Add downloading process bar
- Optimize memory usage for https://github.com/SpeechColab/GigaSpeech/pull/86#issuecomment-914409286

### CODE REVIEW

**Review by dophist — APPROVED** [review]
LGTM

**Review by chenguoguo — COMMENTED** [review]
Is this still WIP or is this ready for review?

**Comment by jimbozhang** [comment]
Still WIP ...

**Comment by jimbozhang** [comment]
May @chaisz19 help to test it? The following script may help:

```python
from speechcolab.datasets.gigaspeech import GigaSpeech

target_dir = '/Data/GigaSpeech3'
password = THE_PASSWORD

GigaSpeech(target_dir).download(password, subset='{XS}', host='magicdata')
```

**Comment by chaisz19** [comment]
Well, It works on the AWS host!

**Pull request merged**
